services:
  cowatch:
    build: .
    container_name: cowatch
    restart: always
    env_file:
      - .env
    ports:
      - "1935:1935"
    volumes:
      - ./sqlite.db:/app/sqlite.db
    labels:
      caddy: watch.pallabdev.in
      caddy.reverse_proxy: "{{upstreams 5678}}"
    networks:
      - default
      - caddy_net

networks:
  caddy_net:
    external: true
  default:
