services:
  cowatch:
    build: .
    container_name: cowatch
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /proc/net/dev:/host_proc/net/dev:ro
    labels:
      caddy: watch.pallabdev.in
      caddy.reverse_proxy: "{{upstreams 5678}}"
    networks:
      - default
      - caddy_net

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always
    environment:
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCENCRYPTION=no
      - MTX_WEBRTCSERVERSSTUN=["stun:stun.l.google.com:19302"]
      - MTX_WEBRTCALLOWORIGINS=["*"]
      - MTX_WEBRTCADDITIONALHOSTS=["watch.pallabdev.in"]
    ports:
      - "8889:8889"
      - "8189:8189/udp"
    networks:
      - default

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: always
    command: turnserver -a -v -n -u guest:somepassword -p 3478 -L 0.0.0.0 -r cowatch.local --no-tls --no-dtls --min-port 50000 --max-port 50050
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50050:50000-50050/udp"
    networks:
      - default

networks:
  caddy_net:
    external: true
  default:
