services:
  cowatch:
    build: .
    container_name: cowatch
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - STREAM_INTERNAL_SOURCE=rtsp://host.docker.internal:8554/live/{streamKey}
      - RTMP_PUBLIC_SERVER=${RTMP_PUBLIC_SERVER:-rtmp://watch.pallabdev.in:1935/live}
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - /proc/net/dev:/host_proc/net/dev:ro
    labels:
      caddy: watch.pallabdev.in
      caddy.reverse_proxy: "{{upstreams 5678}}"
    ports:
      - "40000-40100:40000-40100/udp"
      - "40000-40100:40000-40100/tcp"
    networks:
      - default
      - caddy_net

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always
    network_mode: host
    environment:
      - MTX_RTMP=yes
      - MTX_RTMPADDRESS=:1935
      - MTX_RTSP=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8889
      - MTX_WEBRTCENCRYPTION=no
      - MTX_WEBRTCSERVERSSTUN=["stun:stun.l.google.com:19302"]
      - MTX_WEBRTCALLOWORIGINS=["*"]
      - MTX_WEBRTCADDITIONALHOSTS=["watch.pallabdev.in"]

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: always
    command: turnserver -a -v -n -u guest:somepassword -p 3478 -L 0.0.0.0 -r watch.pallabdev.in -X watch.pallabdev.in --no-tls --no-dtls --min-port 50000 --max-port 50050
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50050:50000-50050/udp"
    networks:
      - default

networks:
  caddy_net:
    external: true
  default:
